# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa598535c280d71249d197b96bddba96ebbb1f9d4dbfb3403f597507b672efa8e0c2bf5aec4146032f6bc76054a1ac1c42e37fa98e23fb7cd836f6c53fb50639

test:
  secret_key_base: d9834a70c2f732918189ae7b570f31913b051b9fc43a40f65e9697adb5479eaef1ed8e7c4cde98a2508c7dfaf7be4a641392acfddd3f83f3dc0e262f9df5375b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
